### ISSUE TITLE
Migrate repos to use libhal 0.2.2

### ISSUE THREAD

**Issue by kammce** [libhal-google/.github#24]
libhal got split up into libhal-mock, libhal-util, libhal-soft (coming soon) when it was upgraded to libhal 0.2.0. libhal 0.2.2 has some bug fixes from the initial refactor. The following repos need to be updated to use the new libhal 0.2.x architecture.

- [x] libarmcortex
- [x] liblpc40xx
- [x] libesp8266
- [x] libhal-util
- [x] libhal-mock
- [x] libhal-starter

**Comment by MaliaLabor** [comment]
All listed repos are all using the new libhal 0.2.x architecture.
