### ISSUE TITLE
Migrate all unit tests to support code coverage

### ISSUE THREAD

**Issue by kammce** [libhal-google/.github#26]
Replace `boost::ut::suite <suite_name> = []() { ...` with `void <suite_name> () { ...` and all those functions in `main.test.cpp`.

Repos to update:

- [x] libarmcortex
- [x] liblpc40xx
- [x] libesp8266
- [x] libhal-util
- [x] libhal-mock
- [x] libhal-starter

**Comment by MaliaLabor** [comment]
.take

**Comment by MaliaLabor** [comment]
All libraries in this list have been migrated to support code coverage
